name: 🐛 Bug Report
description: Something broken that needs fixing
title: "[BUG] "
labels: ["type:bug"]
body:
  - type: markdown
    attributes:
      value: |
        ## Bug Report
        Use this template to report issues that need immediate attention.

  - type: dropdown
    id: track
    attributes:
      label: Track
      description: Which system is affected?
      options:
        - Finance SSC
        - Odoo Platform
        - BI Analytics
        - AI/ML
        - Infrastructure
        - Learning
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How severe is this bug?
      options:
        - 🔥 Critical (production broken)
        - ⚠️ High (major functionality impaired)
        - 📋 Medium (workaround exists)
        - 📝 Low (minor issue)
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: What is broken?
      placeholder: "When I do X, Y happens instead of Z..."
    validations:
      required: true

  - type: textarea
    id: reproduce
    attributes:
      label: Steps to Reproduce
      description: How can we reproduce this bug?
      placeholder: |
        1. Go to...
        2. Click on...
        3. See error...
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What should happen instead?
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: Where does this bug occur?
      placeholder: |
        - Browser: Chrome 120
        - OS: macOS 14
        - Service: Odoo 19.0 / Supabase / etc.
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Error Logs / Screenshots
      description: Paste any relevant error messages or attach screenshots
      placeholder: |
        ```
        Error: Cannot read property 'xyz' of undefined
        ```

  - type: textarea
    id: impact
    attributes:
      label: Business Impact
      description: Who is affected and how?
      placeholder: "8 employees cannot submit expenses, blocking month-end close"
