name: 🔧 Chore
description: Maintenance, refactoring, technical debt
title: "[CHORE] "
labels: ["type:chore"]
body:
  - type: markdown
    attributes:
      value: |
        ## Maintenance Task
        Use this template for technical debt, refactoring, or maintenance work.

  - type: dropdown
    id: track
    attributes:
      label: Track
      description: Which area needs maintenance?
      options:
        - Finance SSC
        - Odoo Platform
        - BI Analytics
        - AI/ML
        - Infrastructure
        - Learning
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: What maintenance work is needed?
      placeholder: "We need to refactor X because Y..."
    validations:
      required: true

  - type: textarea
    id: motivation
    attributes:
      label: Motivation
      description: Why is this important?
      placeholder: |
        - Current state causes...
        - Will improve...
    validations:
      required: true

  - type: textarea
    id: tasks
    attributes:
      label: Tasks
      description: What specific work needs to be done?
      placeholder: |
        - [ ] Task 1
        - [ ] Task 2
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How urgent is this maintenance?
      options:
        - ⚠️ High (blocking future work)
        - 📋 Medium (should do soon)
        - 📝 Low (nice to have)
    validations:
      required: true
